# JobsAdventure Configuration File
# A flexible and customizable jobs plugin for Minecraft servers

# Language settings
language:
  # Available languages: en_US, fr_FR
  # Language files are located in plugins/JobsAdventure/languages/
  locale: "en_US"

# Message display settings
messages:
  # Show XP gain messages to players
  show-xp-gain: true

# Sound effects
sounds:
  level-up: "ENTITY_PLAYER_LEVELUP"
  xp-gain: "ENTITY_EXPERIENCE_ORB_PICKUP"

# General plugin settings
settings:
  # How often to auto-save player data (in seconds)
  save-interval: 300
  
  # Maximum number of jobs a player can have at once
  max-jobs-per-player: 3
  
  # Enable debug logging
  debug: false

# Commands to execute when a player levels up
# Placeholders: {player}, {job}, {level}
level-up-commands:
  - "broadcast {player} reached level {level} in {job}!"
  - "give {player} diamond 1"

# Block protection settings (anti-exploit)
block-protection:
  # Enable block protection to prevent XP farming exploits
  # Uses NBT tags to mark ALL player-placed blocks
  # Blocks placed by players will not give XP when mined
  # Supports both vanilla blocks and Nexo custom blocks
  # (Nexo compatibility is automatic when Nexo plugin is present)
  enabled: true
  
  # Example: How this protects the Miner job from exploits
  # 1. Player places a DIAMOND_ORE block
  # 2. System marks it with NBT tag "player_placed"
  # 3. When player mines it, no XP is awarded (50.0 XP prevented)
  # 4. Natural diamond ore still gives full XP
  # 5. Works with custom Nexo blocks like custom_diamond_ore

# Database configuration (for future use)
database:
  enabled: false
  type: "mysql"
  host: "localhost"
  port: 3306
  database: "jobsadventure"
  username: "username"
  password: "password"