blank_issues_enabled: false
contact_links:
  - name: Wiki Documentation
    url: https://github.com/UniverseStudiosMC/UniverseJobs/wiki
    about: Check the Wiki for documentation and guides before opening an issue
