# Modern GitBook Configuration

# Content structure
root: ./

# Documentation configuration
structure:
  readme: README.md
  summary: SUMMARY.md

# Metadata
title: UniverseJobs Wiki
description: Complete documentation for UniverseJobs - The ultimate jobs plugin for Minecraft

# Site configuration
site:
  title: UniverseJobs Wiki
  description: Complete guide to install, configure and use UniverseJobs
  
# Integrations
integrations:
  github:
    enabled: true
    repository: ax-dev/UniverseJobs
    
  search:
    enabled: true
    
  analytics:
    enabled: false

# PDF configuration
pdf:
  enabled: true
  title: UniverseJobs - Complete Guide
  author: Ax_Dev
  
# Global variables
variables:
  plugin_version: "1.0"
  minecraft_version: "1.21+"
  java_version: "21"
  
# Redirections (if needed)
redirects: {}