name: Auto Version Bump

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'pom.xml'
      - '.github/workflows/auto-version.yml'

jobs:
  version-bump:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          
      - name: Get current version
        id: get_version
        run: |
          CURRENT_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "CURRENT_VERSION=$CURRENT_VERSION" >> $GITHUB_OUTPUT
          echo "Current version: $CURRENT_VERSION"
          
      - name: Calculate next version
        id: next_version
        run: |
          CURRENT_VERSION=${{ steps.get_version.outputs.CURRENT_VERSION }}
          # Split version into major.minor.patch
          IFS='.' read -r MAJOR MINOR PATCH <<< "$CURRENT_VERSION"
          # Increment patch version
          NEW_PATCH=$((PATCH + 1))
          NEW_VERSION="$MAJOR.$MINOR.$NEW_PATCH"
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_OUTPUT
          echo "New version: $NEW_VERSION"
          
      - name: Update version in pom.xml
        run: mvn versions:set -DnewVersion=${{ steps.next_version.outputs.NEW_VERSION }}
        
      - name: Commit version bump
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add pom.xml
          git commit -m "chore: bump version to ${{ steps.next_version.outputs.NEW_VERSION }} [skip ci]"
          
      - name: Push changes
        run: git push
        
      - name: Build with new version
        run: mvn clean package
        
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: JobsAdventure-${{ steps.next_version.outputs.NEW_VERSION }}
          path: target/JobsAdventure-${{ steps.next_version.outputs.NEW_VERSION }}.jar